[package]
name = "docker-intrude"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dockersock = { path = "../dockersock" }
privileges = { path = "../privileges" }
signals = { path = "../signals" }
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
